---
- hosts: newhost
  tasks:
    - name: find files to remove in tmp
      find:
        path: /tmp
        patterns: "*.authorized_keys"
      register: files_to_delete

    - name: remove files from tmp
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files  }}"

    - name: create user
      user: name=ykrest

    - name: fetch key from github
      delegate_to: 127.0.0.1
      get_url: url=https://raw.githubusercontent.com/ykrest/ansible/master/publickey.txt dest=/tmp/ykrest.authorized_keys

    - name: setup authorized_key
      authorized_key: user=ykrest key="{{ lookup('file', '/tmp/ykrest.authorized_keys') }}"
